<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\de4dot.cui\de4dot.cui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <LicenseFiles Include="$(MSBuildThisFileDirectory)\..\..\licenses\*" />
    <LicenseFiles Include="$(MSBuildThisFileDirectory)\..\..\LICENSE" />
  </ItemGroup>

  <Target Name="CopyLicenseFiles_AfterBuild" AfterTargets="AfterBuild">
    <Copy SourceFiles="@(LicenseFiles)" DestinationFolder="$(TargetDir)LICENSES" />
  </Target>

  <Target Name="CopyLicenseFiles_Publish" AfterTargets="Publish">
    <Copy SourceFiles="@(LicenseFiles)" DestinationFolder="$(PublishDir)LICENSES" />
  </Target>

</Project>
